packages:
  - apps/*
  - packages/*
  - packages/config/*
ignoredBuiltDependencies:
  - "@parcel/watcher"
  - "@prisma/client"
  - "@prisma/engines"
  - "@tailwindcss/oxide"
  - argon2
  - esbuild
  - prisma
  - sharp
