import "./globals.css"

import { ApolloWrapper } from "@/lib/apollo-wrapper"
import type { Metadata } from "next"
import { JetBrains_Mono } from "next/font/google"
import { Toaster } from "sonner"

const fontSans = JetBrains_Mono({ subsets: ["latin"], variable: "--font-sans" })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={fontSans.variable}>
      <body>
        <ApolloWrapper>{children}</ApolloWrapper>
        <Toaster theme="dark" richColors />
      </body>
    </html>
  )
}
