import { db } from "../../client"
import { log, logError, logSuccess } from "../fake/logger"

const actionsData = [
  {
    game: "tf",
    code: "flagevent_defended",
    reward_player: 1,
    reward_team: 0,
    team: "",
    description: "Defended the flag",
    for_PlayerActions: "1",
    for_PlayerPlayerActions: "0",
    for_TeamActions: "0",
    for_WorldActions: "0",
  },
  {
    game: "tf",
    code: "flagevent_captured",
    reward_player: 5,
    reward_team: 1,
    team: "",
    description: "Captured the flag",
    for_PlayerActions: "1",
    for_PlayerPlayerActions: "0",
    for_TeamActions: "0",
    for_WorldActions: "0",
  },
  {
    game: "tf",
    code: "flagevent_dropped",
    reward_player: -2,
    reward_team: 0,
    team: "",
    description: "Dropped the flag (while alive)",
    for_PlayerActions: "1",
    for_PlayerPlayerActions: "0",
    for_TeamActions: "0",
    for_WorldActions: "0",
  },
  {
    game: "tf",
    code: "flagevent_dropped_death",
    reward_player: 0,
    reward_team: 0,
    team: "",
    description: "Dropped the flag (on death)",
    for_PlayerActions: "1",
    for_PlayerPlayerActions: "0",
    for_TeamActions: "0",
    for_WorldActions: "0",
  },
  {
    game: "tf",
    code: "flagevent_picked_up",
    reward_player: 2,
    reward_team: 0,
    team: "",
    description: "Picked up the flag",
    for_PlayerActions: "1",
    for_PlayerPlayerActions: "0",
    for_TeamActions: "0",
    for_WorldActions: "0",
  },
  {
    game: "tf",
    code: "killedobject_obj_teleporter",
    reward_player: 2,
    reward_team: 0,
    team: "",
    description: "Destroyed a teleporter",
    for_PlayerActions: "1",
    for_PlayerPlayerActions: "0",
    for_TeamActions: "0",
    for_WorldActions: "0",
  },
  {
    game: "tf",
    code: "killedobject_obj_dispenser",
    reward_player: 3,
    reward_team: 0,
    team: "",
    description: "Destroyed a dispenser",
    for_PlayerActions: "1",
    for_PlayerPlayerActions: "0",
    for_TeamActions: "0",
    for_WorldActions: "0",
  },
  {
    game: "tf",
    code: "killedobject_obj_sentrygun",
    reward_player: 4,
    reward_team: 0,
    team: "",
    description: "Destroyed a sentry gun",
    for_PlayerActions: "1",
    for_PlayerPlayerActions: "0",
    for_TeamActions: "0",
    for_WorldActions: "0",
  },
  {
    game: "tf",
    code: "killedobject_obj_sentrygun_mini",
    reward_player: 4,
    reward_team: 0,
    team: "",
    description: "Destroyed a mini sentry gun",
    for_PlayerActions: "1",
    for_PlayerPlayerActions: "0",
    for_TeamActions: "0",
    for_WorldActions: "0",
  },
  {
    game: "tf",
    code: "builtobject_obj_teleporter",
    reward_player: 2,
    reward_team: 0,
    team: "",
    description: "Built a teleporter",
    for_PlayerActions: "1",
    for_PlayerPlayerActions: "0",
    for_TeamActions: "0",
    for_WorldActions: "0",
  },
  {
    game: "tf",
    code: "builtobject_obj_dispenser",
    reward_player: 3,
    reward_team: 0,
    team: "",
    description: "Built a dispenser",
    for_PlayerActions: "1",
    for_PlayerPlayerActions: "0",
    for_TeamActions: "0",
    for_WorldActions: "0",
  },
  {
    game: "tf",
    code: "builtobject_obj_sentrygun",
    reward_player: 3,
    reward_team: 0,
    team: "",
    description: "Built a sentry gun",
    for_PlayerActions: "1",
    for_PlayerPlayerActions: "0",
    for_TeamActions: "0",
    for_WorldActions: "0",
  },
  {
    game: "tf",
    code: "builtobject_obj_sentrygun_mini",
    reward_player: 3,
    reward_team: 0,
    team: "",
    description: "Built a mini sentry gun",
    for_PlayerActions: "1",
    for_PlayerPlayerActions: "0",
    for_TeamActions: "0",
    for_WorldActions: "0",
  },
  {
    game: "tf",
    code: "captureblocked",
    reward_player: 1,
    reward_team: 0,
    team: "",
    description: "Capture Blocked",
    for_PlayerActions: "1",
    for_PlayerPlayerActions: "0",
    for_TeamActions: "0",
    for_WorldActions: "0",
  },
  {
    game: "tf",
    code: "pointcaptured",
    reward_player: 5,
    reward_team: 5,
    team: "",
    description: "Point Captured",
    for_PlayerActions: "1",
    for_PlayerPlayerActions: "0",
    for_TeamActions: "1",
    for_WorldActions: "0",
  },
  {
    game: "tf",
    code: "kill assist",
    reward_player: 2,
    reward_team: 0,
    team: "",
    description: "Kill Assist",
    for_PlayerActions: "1",
    for_PlayerPlayerActions: "0",
    for_TeamActions: "0",
    for_WorldActions: "0",
  },
  {
    game: "tf",
    code: "builtobject_obj_attachment_sapper",
    reward_player: 2,
    reward_team: 0,
    team: "",
    description: "Attached a Sapper",
    for_PlayerActions: "1",
    for_PlayerPlayerActions: "0",
    for_TeamActions: "0",
    for_WorldActions: "0",
  },
  {
    game: "tf",
    code: "killedobject_obj_attachment_sapper",
    reward_player: 1,
    reward_team: 0,
    team: "",
    description: "Removed a Sapper",
    for_PlayerActions: "1",
    for_PlayerPlayerActions: "0",
    for_TeamActions: "0",
    for_WorldActions: "0",
  },
  {
    game: "tf",
    code: "chargedeployed",
    reward_player: 1,
    reward_team: 0,
    team: "",
    description: "Ubercharge",
    for_PlayerActions: "1",
    for_PlayerPlayerActions: "0",
    for_TeamActions: "0",
    for_WorldActions: "0",
  },
  {
    game: "tf",
    code: "domination",
    reward_player: 5,
    reward_team: 0,
    team: "",
    description: "Domination",
    for_PlayerActions: "0",
    for_PlayerPlayerActions: "1",
    for_TeamActions: "0",
    for_WorldActions: "0",
  },
  {
    game: "tf",
    code: "revenge",
    reward_player: 3,
    reward_team: 0,
    team: "",
    description: "Revenge",
    for_PlayerActions: "0",
    for_PlayerPlayerActions: "1",
    for_TeamActions: "0",
    for_WorldActions: "0",
  },
  {
    game: "tf",
    code: "Round_Win",
    reward_player: 0,
    reward_team: 10,
    team: "",
    description: "Round Win",
    for_PlayerActions: "0",
    for_PlayerPlayerActions: "0",
    for_TeamActions: "1",
    for_WorldActions: "0",
  },
  {
    game: "tf",
    code: "Mini_Round_Win",
    reward_player: 0,
    reward_team: 5,
    team: "",
    description: "Mini-Round Win",
    for_PlayerActions: "0",
    for_PlayerPlayerActions: "0",
    for_TeamActions: "1",
    for_WorldActions: "0",
  },
  {
    game: "tf",
    code: "owner_killedobject_obj_sentrygun",
    reward_player: -3,
    reward_team: 0,
    team: "",
    description: "Disassembled a sentry gun",
    for_PlayerActions: "1",
    for_PlayerPlayerActions: "0",
    for_TeamActions: "0",
    for_WorldActions: "0",
  },
  {
    game: "tf",
    code: "owner_killedobject_obj_sentrygun_mini",
    reward_player: -3,
    reward_team: 0,
    team: "",
    description: "Disassembled a mini sentry gun",
    for_PlayerActions: "1",
    for_PlayerPlayerActions: "0",
    for_TeamActions: "0",
    for_WorldActions: "0",
  },
  {
    game: "tf",
    code: "owner_killedobject_obj_dispenser",
    reward_player: -3,
    reward_team: 0,
    team: "",
    description: "Disassembled a dispenser",
    for_PlayerActions: "1",
    for_PlayerPlayerActions: "0",
    for_TeamActions: "0",
    for_WorldActions: "0",
  },
  {
    game: "tf",
    code: "owner_killedobject_obj_teleporter",
    reward_player: -2,
    reward_team: 0,
    team: "",
    description: "Disassembled a teleporter",
    for_PlayerActions: "1",
    for_PlayerPlayerActions: "0",
    for_TeamActions: "0",
    for_WorldActions: "0",
  },
  {
    game: "tf",
    code: "owner_killedobject_obj_attachment_sapper",
    reward_player: -2,
    reward_team: 0,
    team: "",
    description: "Console-killed sapper",
    for_PlayerActions: "1",
    for_PlayerPlayerActions: "0",
    for_TeamActions: "0",
    for_WorldActions: "0",
  },
  {
    game: "tf",
    code: "backstab",
    reward_player: 2,
    reward_team: 0,
    team: "",
    description: "Backstab Kill",
    for_PlayerActions: "1",
    for_PlayerPlayerActions: "0",
    for_TeamActions: "0",
    for_WorldActions: "0",
  },
  {
    game: "tf",
    code: "headshot",
    reward_player: 2,
    reward_team: 0,
    team: "",
    description: "Headshot Kill",
    for_PlayerActions: "1",
    for_PlayerPlayerActions: "0",
    for_TeamActions: "0",
    for_WorldActions: "0",
  },
  {
    game: "tf",
    code: "kill_assist_medic",
    reward_player: 3,
    reward_team: 0,
    team: "",
    description: "Kill Assist - Medic",
    for_PlayerActions: "1",
    for_PlayerPlayerActions: "0",
    for_TeamActions: "0",
    for_WorldActions: "0",
  },
  {
    game: "tf",
    code: "kill_streak_2",
    reward_player: 1,
    reward_team: 0,
    team: "",
    description: "Double Kill (2 kills)",
    for_PlayerActions: "1",
    for_PlayerPlayerActions: "0",
    for_TeamActions: "0",
    for_WorldActions: "0",
  },
  {
    game: "tf",
    code: "kill_streak_3",
    reward_player: 2,
    reward_team: 0,
    team: "",
    description: "Triple Kill (3 kills)",
    for_PlayerActions: "1",
    for_PlayerPlayerActions: "0",
    for_TeamActions: "0",
    for_WorldActions: "0",
  },
  {
    game: "tf",
    code: "kill_streak_4",
    reward_player: 3,
    reward_team: 0,
    team: "",
    description: "Domination (4 kills)",
    for_PlayerActions: "1",
    for_PlayerPlayerActions: "0",
    for_TeamActions: "0",
    for_WorldActions: "0",
  },
  {
    game: "tf",
    code: "kill_streak_5",
    reward_player: 4,
    reward_team: 0,
    team: "",
    description: "Rampage (5 kills)",
    for_PlayerActions: "1",
    for_PlayerPlayerActions: "0",
    for_TeamActions: "0",
    for_WorldActions: "0",
  },
  {
    game: "tf",
    code: "kill_streak_6",
    reward_player: 5,
    reward_team: 0,
    team: "",
    description: "Mega Kill (6 kills)",
    for_PlayerActions: "1",
    for_PlayerPlayerActions: "0",
    for_TeamActions: "0",
    for_WorldActions: "0",
  },
  {
    game: "tf",
    code: "kill_streak_7",
    reward_player: 6,
    reward_team: 0,
    team: "",
    description: "Ownage (7 kills)",
    for_PlayerActions: "1",
    for_PlayerPlayerActions: "0",
    for_TeamActions: "0",
    for_WorldActions: "0",
  },
  {
    game: "tf",
    code: "kill_streak_8",
    reward_player: 7,
    reward_team: 0,
    team: "",
    description: "Ultra Kill (8 kills)",
    for_PlayerActions: "1",
    for_PlayerPlayerActions: "0",
    for_TeamActions: "0",
    for_WorldActions: "0",
  },
  {
    game: "tf",
    code: "kill_streak_9",
    reward_player: 8,
    reward_team: 0,
    team: "",
    description: "Killing Spree (9 kills)",
    for_PlayerActions: "1",
    for_PlayerPlayerActions: "0",
    for_TeamActions: "0",
    for_WorldActions: "0",
  },
  {
    game: "tf",
    code: "kill_streak_10",
    reward_player: 9,
    reward_team: 0,
    team: "",
    description: "Monster Kill (10 kills)",
    for_PlayerActions: "1",
    for_PlayerPlayerActions: "0",
    for_TeamActions: "0",
    for_WorldActions: "0",
  },
  {
    game: "tf",
    code: "kill_streak_11",
    reward_player: 10,
    reward_team: 0,
    team: "",
    description: "Ultra Kill (8 kills)",
    for_PlayerActions: "1",
    for_PlayerPlayerActions: "0",
    for_TeamActions: "0",
    for_WorldActions: "0",
  },
]
export const seedActions = async () => {
  try {
    log("Seeding actions...")

    await db.action.deleteMany()
    const result = await db.action.createMany({
      data: actionsData,
      skipDuplicates: true,
    })

    logSuccess(`Seeded ${result.count} actions.`)
  } catch (error) {
    logError(`Failed to seed actions: ${JSON.stringify(error)}`)
    throw error
  }
}
