// Mock data with gradient colors for each player
export const topPlayers = {
  today: [
    {
      id: 1,
      name: "FragMaster",
      avatar: "/placeholder.svg?height=24&width=24",
      kd: 2.8,
      points: 1247,
      rank: 1,
      gradient: "from-yellow-400 to-orange-500",
    },
    {
      id: 2,
      name: "SniperElite",
      avatar: "/placeholder.svg?height=24&width=24",
      kd: 2.3,
      points: 1156,
      rank: 2,
      gradient: "from-blue-400 to-cyan-500",
    },
    {
      id: 3,
      name: "RushKing",
      avatar: "/placeholder.svg?height=24&width=24",
      kd: 1.9,
      points: 1089,
      rank: 3,
      gradient: "from-purple-400 to-pink-500",
    },
    {
      id: 4,
      name: "HeadHunter",
      avatar: "/placeholder.svg?height=24&width=24",
      kd: 2.1,
      points: 987,
      rank: 4,
      gradient: "from-red-400 to-rose-500",
    },
    {
      id: 5,
      name: "CyberNinja",
      avatar: "/placeholder.svg?height=24&width=24",
      kd: 1.7,
      points: 923,
      rank: 5,
      gradient: "from-green-400 to-emerald-500",
    },
  ],
  week: [
    {
      id: 1,
      name: "ProGamer99",
      avatar: "/placeholder.svg?height=24&width=24",
      kd: 3.2,
      points: 8947,
      rank: 1,
      gradient: "from-yellow-400 to-orange-500",
    },
    {
      id: 2,
      name: "FragMaster",
      avatar: "/placeholder.svg?height=24&width=24",
      kd: 2.8,
      points: 7234,
      rank: 2,
      gradient: "from-blue-400 to-cyan-500",
    },
    {
      id: 3,
      name: "EliteSniper",
      avatar: "/placeholder.svg?height=24&width=24",
      kd: 2.6,
      points: 6891,
      rank: 3,
      gradient: "from-purple-400 to-pink-500",
    },
    {
      id: 4,
      name: "RushKing",
      avatar: "/placeholder.svg?height=24&width=24",
      kd: 2.4,
      points: 6234,
      rank: 4,
      gradient: "from-red-400 to-rose-500",
    },
    {
      id: 5,
      name: "CyberWarrior",
      avatar: "/placeholder.svg?height=24&width=24",
      kd: 2.2,
      points: 5987,
      rank: 5,
      gradient: "from-green-400 to-emerald-500",
    },
  ],
  alltime: [
    {
      id: 1,
      name: "LegendaryPro",
      avatar: "/placeholder.svg?height=24&width=24",
      kd: 4.1,
      points: 45892,
      rank: 1,
      gradient: "from-yellow-400 to-orange-500",
    },
    {
      id: 2,
      name: "FragGod",
      avatar: "/placeholder.svg?height=24&width=24",
      kd: 3.8,
      points: 42156,
      rank: 2,
      gradient: "from-blue-400 to-cyan-500",
    },
    {
      id: 3,
      name: "SniperKing",
      avatar: "/placeholder.svg?height=24&width=24",
      kd: 3.6,
      points: 38947,
      rank: 3,
      gradient: "from-purple-400 to-pink-500",
    },
    {
      id: 4,
      name: "ProGamer99",
      avatar: "/placeholder.svg?height=24&width=24",
      kd: 3.4,
      points: 35234,
      rank: 4,
      gradient: "from-red-400 to-rose-500",
    },
    {
      id: 5,
      name: "EliteFrag",
      avatar: "/placeholder.svg?height=24&width=24",
      kd: 3.2,
      points: 32891,
      rank: 5,
      gradient: "from-green-400 to-emerald-500",
    },
  ],
}

export const activeServers = [
  {
    id: 1,
    name: "FragZone Elite",
    map: "de_dust2",
    players: "24/32",
    status: "online",
    ping: 12,
    region: "US East",
  },
  {
    id: 2,
    name: "Cyber Arena Pro",
    map: "de_inferno",
    players: "0/24",
    status: "offline",
    ping: 28,
    region: "US West",
  },
  {
    id: 3,
    name: "Terminal Gaming",
    map: "de_mirage",
    players: "16/20",
    status: "online",
    ping: 45,
    region: "EU West",
  },
  {
    id: 4,
    name: "Matrix Battleground",
    map: "de_cache",
    players: "12/16",
    status: "online",
    ping: 33,
    region: "US Central",
  },
  {
    id: 5,
    name: "Neon Servers",
    map: "de_overpass",
    players: "8/16",
    status: "online",
    ping: 67,
    region: "Asia",
  },
  {
    id: 6,
    name: "Elite Combat Zone",
    map: "de_train",
    players: "20/24",
    status: "online",
    ping: 19,
    region: "US East",
  },
  {
    id: 7,
    name: "Pro Gaming Hub",
    map: "de_cobblestone",
    players: "14/20",
    status: "online",
    ping: 52,
    region: "EU Central",
  },
]

export const killFeed = [
  {
    id: 1,
    killer: "FragMaster",
    victim: "NoobSlayer",
    weapon: "AK-47",
    map: "de_dust2",
    time: "2s",
  },
  {
    id: 2,
    killer: "SniperElite",
    victim: "RushKing",
    weapon: "AWP",
    map: "de_inferno",
    time: "5s",
  },
  {
    id: 3,
    killer: "CyberNinja",
    victim: "HeadHunter",
    weapon: "M4A4",
    map: "de_mirage",
    time: "8s",
  },
  {
    id: 4,
    killer: "ProGamer99",
    victim: "FragMaster",
    weapon: "Deagle",
    map: "de_dust2",
    time: "12s",
  },
  {
    id: 5,
    killer: "EliteSniper",
    victim: "CyberWarrior",
    weapon: "AWP",
    map: "de_cache",
    time: "15s",
  },
  {
    id: 6,
    killer: "RushKing",
    victim: "CyberNinja",
    weapon: "M4A1-S",
    map: "de_mirage",
    time: "18s",
  },
  {
    id: 7,
    killer: "HeadHunter",
    victim: "ProGamer99",
    weapon: "AK-47",
    map: "de_inferno",
    time: "22s",
  },
  {
    id: 8,
    killer: "FragMaster",
    victim: "EliteSniper",
    weapon: "AWP",
    map: "de_dust2",
    time: "25s",
  },
  {
    id: 9,
    killer: "CyberWarrior",
    victim: "SniperElite",
    weapon: "M4A4",
    map: "de_cache",
    time: "28s",
  },
  {
    id: 10,
    killer: "ProGamer99",
    victim: "RushKing",
    weapon: "AK-47",
    map: "de_inferno",
    time: "32s",
  },
]

export const recentMatches = [
  {
    id: 1,
    map: "de_dust2",
    score: "16-14",
    team1: "Cyber Elite",
    team2: "Frag Masters",
    mvp: "FragMaster",
    time: "2h ago",
  },
  {
    id: 2,
    map: "de_inferno",
    score: "16-12",
    team1: "Terminal Squad",
    team2: "Matrix Clan",
    mvp: "SniperElite",
    time: "4h ago",
  },
  {
    id: 3,
    map: "de_mirage",
    score: "16-8",
    team1: "Pro Gamers",
    team2: "Rush Kings",
    mvp: "ProGamer99",
    time: "6h ago",
  },
  {
    id: 4,
    map: "de_cache",
    score: "16-11",
    team1: "Elite Squad",
    team2: "Cyber Warriors",
    mvp: "EliteSniper",
    time: "8h ago",
  },
]

export const featuredPlayer = {
  name: "FragMaster",
  avatar: "/placeholder.svg?height=48&width=48",
  rank: 1,
  kd: 2.8,
  points: 1247,
  matches: 156,
  wins: 89,
  recentActivity: [
    "30-kill streak on de_dust2",
    "Won FragZone Tournament #47",
    "Reached #1 daily ranking",
  ],
}
